### ISSUE TITLE
`since`와 `version` 커맨드의 사용에 관한 질문

### ISSUE THREAD

**Issue by heejongahn** [toss/yarn-plugin-workspace-since#5]
안녕하세요. 유용한 플러그인 만들어주셔서 감사합니다. 
`since`와 `version` 커맨드의 사용에 관한 질문이 있어서 이슈를 남겨봅니다.

제가 달성하고픈 워크플로우는 다음과 같습니다.

1. PR 이 생성되면 `main` 으로부터 변경된 사항이 있는 패키지(와 그에 의존하는 패키지) 를 `test` 한다
2. `main`에 머지되면 마지막으로 배포된 시점 (`latest` 태그) 으로부터 변경된 사항이 있는 패키지의 버전을 올린다
3. 버전이 올라간 패키지들을 배포하고, `latest` 태그를 업데이트한다.

현재는 각각

1. `yarn workspaces since run test refs/remotes/origin/main`
2. `yarn workspaces since version refs/tags/latest` (이후 버전 변경사항을 커밋)
3. `yarn workspaces since run 'npm publish' $(git rev-parse HEAD~1)`

같은 느낌을 생각 중인데요.

이 때 예를 들어 어떤 PR에 `fix(a): 버그 픽스` 커밋이 존재하고 `b` 패키지가 `a` 패키지에 의존하는 상황이라면,

- 2번 스텝에서는 커밋이 존재하는 `a` 패키지만 버전이 업데이트 됩니다. 
- 3번 스텝에서는 `a`와 `a`에 의존하는 `b` 모두에서 `npm publish`를 시도합니다.
- 하지만 `b` 패키지는 컨벤셔널 커밋에 의해 버전이 올라가지 않았으므로 동일한 버전을 재배포하려는 셈이 되어, `You cannot publish over the previously published versions: x.y.z.` 버그와 함께 배포에 실패합니다.
- `b` 패키지의 버전을 올려주기 위해 `fix(b): 버전 업데이트` 등의 커밋을 만들 수 있겠지만, 버전 업그레이드를 위해 의미없는 커밋이 만들어집니다.
- 더군다나, 현재는 [하나의 커밋이 영향을 주는 패키지를 최대 하나만](https://github.com/toss/yarn-plugin-workspace-since/blob/main/sources/ConventionalCommits/ConventionalCommit.ts#L24) 명시 가능하므로 위의 방법을 사용하려면 의존하는 패키지가 많아질수록 버전 업만을 위해 만들어야 하는 커밋의 수가 기하급수적으로 늘어납니다.

이러한 문제를 맞닥뜨린 상황입니다.

혹시 제가 커맨드를 의도와 다르게 사용하고 있는 걸까요? 그게 아니라면 이러한 문제를 해결할 수 있는 방법이 있으면 알려주시면 감사하겠습니다. 비슷한 목적을 달성할 수 있는 다른 워크플로우가 있다면 워크플로우를 변경할 의향도 있습니다. 🙇

**Comment by HyunSeob** [comment]
@heejongahn 

안녕하세요 희종님 ! 플러그인에 관심 가져주셔서 감사합니다 🙇 

우선 말씀하신 상황에서 배포가 안되는 문제를 해결하기 위해서는 (당장은 좀 아쉽지만) `--ignore-errors` 옵션을 사용할 수 있습니다.
`yarn workspaces since run 'npm publish' $(git rev-parse HEAD~1) --ignore-errors` <- 이렇게 하면 에러는 무시되므로 `a`는 배포에 성공합니다. 하지만.. 솔직히 별로긴 하죠..
이 부분은 현재 `run` 커맨드가 항상 의존하는 모듈까지 명령어를 실행하기 때문에 발생하는 문제이기도 해서, 의존하고 있는 모듈은 대상으로 넣지 않는 옵션은 추가하려 합니다.

이렇게해도 희종님이 말씀하신 상황에서 `a` 패키지만 배포가 될텐데요. 꼭 `b` 패키지까지 배포하고 싶으신 상황이라면 `version` 커맨드에 "버전을 변경하는 대상에 의존하는 모듈도 같이 버전을 변경하는" 옵션을 추가하는 변경이 필요할 것 같습니다.

말씀하신 내용이 원래 생각했던 유즈케이스가 아니기는한데, 있을 법한 니즈이기는 해서 천천히 옵션을 추가해보겠습니다. 아니면 기여해주시는 것도 물론 환영합니다!

**Comment by heejongahn** [comment]
답변 감사합니다!

> 이 부분은 현재 run 커맨드가 항상 의존하는 모듈까지 명령어를 실행하기 때문에 발생하는 문제이기도 해서, 의존하고 있는 모듈은 대상으로 넣지 않는 옵션은 추가하려 합니다.

사실 이 옵션을 요청드릴까 했는데 이미 다 계획이 있으셨군요.

> "버전을 변경하는 대상에 의존하는 모듈도 같이 버전을 변경하는" 옵션을 추가

이것은 저도 이게 맞나 아리까리해서 고민중인데, 혹시 필요하다 싶으면 기여 각을 재보겠습니다. (`@tossteam` 스코프 의존성도 사라졌군요 👍 )

**Comment by heejongahn** [comment]
궁금한 점이 해소되어서 이슈는 닫겠습니다~!
